#!/bin/sh -euC
## Copyright 2018 Dmitry Bogatov <KAction@gnu.org>
## 
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -euC; export LC_ALL=C

readonly src='debian/tests/files/read-back.c'
readonly exe="${AUTOPKGTEST_TMP:-/tmp}/read-back"
readonly db="${AUTOPKGTEST_TMP:-/tmp}/example.gdbm"

gcc "${src}" -lgdbm -o "${exe}"
"${exe}" "${db}"

if [ "$(dpkg -s dietlibc-dev | grep -o installed)" = installed ] \
    && ! dpkg-vendor --derives-from Ubuntu ; then
    
    diet gcc "${src}" -lgdbm -o "${exe}"
    "${exe}" "${db}"
fi
