image: registry.gitlab.com/eighthave/ci-image-git-buildpackage:latest
pages:
  stage: deploy
  artifacts:
    paths:
      - public
  script:
    - gitlab-ci-enable-experimental
    - gitlab-ci-git-buildpackage
    - gitlab-ci-lintian
    - gitlab-ci-autopkgtest
    - gitlab-ci-aptly
